[unstable] # Rust Night features
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-bare_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"